services:
  api:
    container_name: product-crud-api
    build:
      context: ..
      dockerfile: docker/Dockerfile.app.dev
    env_file:
      - ../config/app.env
    depends_on:
      - redis
      - postgres
    links:
      - redis
      - postgres

  redis:
    container_name: product-crud-redis
    image: redis
    env_file:
      - ../config/redis.env
    ports:
      - 6379:6379

  postgres:
    container_name: product-crud-postgres
    image: postgres
    volumes:
      - ../volumes/postgres/data:/var/lib/postgresql/data
    env_file:
      - ../config/postgres.env
    ports:
      - 5432:5432
