FROM node:18-alpine as builder
USER node
WORKDIR /app
COPY --chown=node:node app/package.json .
RUN yarn install
COPY --chown=node:node app .
RUN yarn build
 
FROM node:18-alpine
USER node
ENV NODE_ENV=prod
WORKDIR /app
COPY --from=builder --chown=node:node /app/package.json .
EXPOSE 3000
RUN yarn install --production=true
COPY --from=builder --chown=node:node /app/prisma .
COPY --from=builder --chown=node:node /app/dist dist
CMD [ "yarn", "start:prod" ]