name: Run Linter
on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - main
      - develop

jobs:
  app-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Installing modules
      run: cd app && yarn install

    - name: Running linter
      run: cd app && yarn lint

  # worker-lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Installing modules
  #     run: cd worker && yarn install

  #   - name: Running linter
  #     run: cd worker && yarn lint